version: '3.5'

services:
  app-go:
    build: ./
    ports:
      - ${APP_PORT}:${APP_PORT}
    restart: on-failure
    volumes:
      - ./:/app
    depends_on:
      - app-mysql
    networks:
      - app-network

  app-mysql:
     image: mysql:5.7
     container_name: app-mysql
     restart: always
     ports:
       - ${DB_PORT}:3306
     environment:
       - MYSQL_ROOT_HOST=${DB_HOST}
       - MYSQL_USER=${DB_USER}
       - MYSQL_PASSWORD=${DB_PASS}
       - MYSQL_DATABASE=${DB_NAME}
       - MYSQL_ROOT_PASSWORD=${DB_PASS}
     volumes:
       - app_mysql:/var/lib/mysql
     networks:
       - app-network

volumes:
  app_mysql:

# Networks to be created to facilitate communication between containers
networks:
  app-network:
    driver: bridge