version: '3.5'

services:
  db-mysql:
     image: mysql:5.7
     container_name: sherman-mysql
     restart: always
     ports:
       - 3306:3306
     environment:
       - MYSQL_ROOT_HOST=${DB_HOST}
       - MYSQL_USER=${DB_USER}
       - MYSQL_PASSWORD=${DB_PASS}
       - MYSQL_DATABASE=${DB_NAME}
       - MYSQL_ROOT_PASSWORD=${DB_PASS}
     volumes:
       - database_mysql:/var/lib/mysql

volumes:
  database_mysql: