// Code generated by mockery v2.0.0-alpha.2. DO NOT EDIT.

package mocks

import (
	config "sherman/src/service/config"

	mock "github.com/stretchr/testify/mock"
)

// Config is an autogenerated mock type for the Config type
type Config struct {
	mock.Mock
}

// Get provides a mock function with given fields:
func (_m *Config) Get() config.GlobalConfig {
	ret := _m.Called()

	var r0 config.GlobalConfig
	if rf, ok := ret.Get(0).(func() config.GlobalConfig); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(config.GlobalConfig)
	}

	return r0
}

// Load provides a mock function with given fields: cfg
func (_m *Config) Load(cfg config.GlobalConfig) {
	_m.Called(cfg)
}
