// Code generated by mockery v2.0.0-alpha.2. DO NOT EDIT.

package mocks

import (
	auth "sherman/src/domain/auth"

	mock "github.com/stretchr/testify/mock"
)

// Presenter is an autogenerated mock type for the Presenter type
type Presenter struct {
	mock.Mock
}

// PresentUser provides a mock function with given fields: user
func (_m *Presenter) PresentUser(user *auth.User) auth.PresentedUser {
	ret := _m.Called(user)

	var r0 auth.PresentedUser
	if rf, ok := ret.Get(0).(func(*auth.User) auth.PresentedUser); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Get(0).(auth.PresentedUser)
	}

	return r0
}
