// Code generated by mockery v2.0.0-alpha.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ResponseService is an autogenerated mock type for the ResponseService type
type ResponseService struct {
	mock.Mock
}

// GetBody provides a mock function with given fields:
func (_m *ResponseService) GetBody() map[string]interface{} {
	ret := _m.Called()

	var r0 map[string]interface{}
	if rf, ok := ret.Get(0).(func() map[string]interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	return r0
}

// GetStatus provides a mock function with given fields:
func (_m *ResponseService) GetStatus() int {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// SetData provides a mock function with given fields: status, data
func (_m *ResponseService) SetData(status int, data map[string]interface{}) {
	_m.Called(status, data)
}

// SetError provides a mock function with given fields: status, err
func (_m *ResponseService) SetError(status int, err string) {
	_m.Called(status, err)
}

// SetErrors provides a mock function with given fields: status, errs
func (_m *ResponseService) SetErrors(status int, errs map[string]string) {
	_m.Called(status, errs)
}

// SetInternalServerError provides a mock function with given fields:
func (_m *ResponseService) SetInternalServerError() {
	_m.Called()
}
