// Code generated by mockery v2.0.0-alpha.2. DO NOT EDIT.

package mocks

import (
	auth "sherman/src/domain/auth"

	mock "github.com/stretchr/testify/mock"
)

// UserUseCase is an autogenerated mock type for the UserUseCase type
type UserUseCase struct {
	mock.Mock
}

// GetUserByID provides a mock function with given fields: id
func (_m *UserUseCase) GetUserByID(id string) (auth.User, error) {
	ret := _m.Called(id)

	var r0 auth.User
	if rf, ok := ret.Get(0).(func(string) auth.User); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(auth.User)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Register provides a mock function with given fields: user
func (_m *UserUseCase) Register(user *auth.User) error {
	ret := _m.Called(user)

	var r0 error
	if rf, ok := ret.Get(0).(func(*auth.User) error); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// VerifyCredentials provides a mock function with given fields: user
func (_m *UserUseCase) VerifyCredentials(user *auth.User) (auth.User, error) {
	ret := _m.Called(user)

	var r0 auth.User
	if rf, ok := ret.Get(0).(func(*auth.User) auth.User); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Get(0).(auth.User)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*auth.User) error); ok {
		r1 = rf(user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
