# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      # APP
      APP_DEBUG: false
      APP_PORT: 5000
      APP_ADDR: :5000

      # DATABASE
      DB_DRIVER: mysql
      DB_NAME: sherman
      DB_USER: db_user
      DB_PASS: db_password
      DB_HOST: app-mysql
      DB_PORT: 3306
      DB_EXPOSED_PORT: 5001

      #JWT
      JWT_SECRET: jwt_secret

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: setup
      run: |
        echo === CI -> Builing ===
        docker-compose build
        docker-compose up -d
        echo === CI -> Running Tests ===
        bin/exec test
        echo === CI -> Linting ===
        bin/lint
        echo === CI -> Stopping Containers ===
        bin/down
        echo === CI -> Tasks Completed ===
        
        
