name: pull-request

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # APP
      APP_DEBUG: false
      APP_PORT: 5000
      APP_ADDR: :5000
      # DATABASE
      DB_DRIVER: sqlite3
      DB_PATH: "./src/app/database/testDB.db"
      #JWT
      JWT_SECRET: jwt_secret

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.14'
    - name: Run test/lint
      run: |
        echo === CI -> Generating mocks ===
        bin/mockery
        echo === CI -> Builing ===
        go mod tidy
        go build main.go
        echo === CI -> Running Tests ===
        bin/cmd/test
        echo === CI -> Linting ===
        bin/lint
        echo === CI -> Tasks Completed ===
