name: pull-request

on:
  pull_request:
    branches: [ test ]

jobs:
  pull-request:
    runs-on: ubuntu-latest
    env:
      # APP
      APP_DEBUG: false
      APP_PORT: 5000
      APP_ADDR: :5000
      # DATABASE
      DB_DRIVER: sqlite3
      DB_PATH: "./src/app/database/testDB.db"
      #JWT
      JWT_SECRET: jwt_secret

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.14'
    - name: Build
      run: |
        bin/mockery
        go mod tidy
        go build main.go
    - name: Test
      run: bin/cmd/test
    - name: Lint
      run: bin/lint

