name: push

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  push:
    runs-on: ubuntu-latest
    env:
      # APP
      APP_DEBUG: false
      APP_PORT: 5000
      APP_ADDR: :5000
      # DATABASE
      DB_DRIVER: sqlite3
      DB_PATH: "./src/app/database/testDB.db"
      #JWT
      JWT_SECRET: jwt_secret

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.14'
    - name: CHECK
        ls -la ${{github.workspace}}
        ${{ secrets.CC_TEST_REPORTER_ID }}
    - name: Build
      run: |
        bin/mockery
        go mod tidy
        go build main.go
    - name: Test & Publish Coverage
      uses: paambaati/codeclimate-action@v2.6.0
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      with:
        coverageCommand: bin/cmd/test
        coverageLocations: ${{github.workspace}}/coverage/coverage.out
    - name: Lint
      run: bin/lint